// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bloomfilter

import (
	mock "github.com/stretchr/testify/mock"
	"golang.a2z.com/demanddriventrafficevaluator/interfaces"
)

// NewBloomFilterProviderInterface creates a new instance of BloomFilterProviderInterface.
// It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBloomFilterProviderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BloomFilterProviderInterface {
	mock := &BloomFilterProviderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BloomFilterProviderInterface is an autogenerated mock type for the BloomFilterProviderInterface type
type BloomFilterProviderInterface struct {
	mock.Mock
}

type BloomFilterProviderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *BloomFilterProviderInterface) EXPECT() *BloomFilterProviderInterface_Expecter {
	return &BloomFilterProviderInterface_Expecter{mock: &_m.Mock}
}

// Provide provides a mock function for the type BloomFilterProviderInterface
func (_mock *BloomFilterProviderInterface) Provide(modelIdentifier string, features []interfaces.ModelFeature, defaultValue float32) (*interfaces.ModelResult, error) {
	ret := _mock.Called(modelIdentifier, features, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 *interfaces.ModelResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []interfaces.ModelFeature, float32) (*interfaces.ModelResult, error)); ok {
		return returnFunc(modelIdentifier, features, defaultValue)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []interfaces.ModelFeature, float32) *interfaces.ModelResult); ok {
		r0 = returnFunc(modelIdentifier, features, defaultValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.ModelResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []interfaces.ModelFeature, float32) error); ok {
		r1 = returnFunc(modelIdentifier, features, defaultValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BloomFilterProviderInterface_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type BloomFilterProviderInterface_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
//   - modelIdentifier
//   - features
//   - defaultValue
func (_e *BloomFilterProviderInterface_Expecter) Provide(modelIdentifier interface{}, features interface{}, defaultValue interface{}) *BloomFilterProviderInterface_Provide_Call {
	return &BloomFilterProviderInterface_Provide_Call{Call: _e.mock.On("Provide", modelIdentifier, features, defaultValue)}
}

func (_c *BloomFilterProviderInterface_Provide_Call) Run(run func(modelIdentifier string, features []interfaces.ModelFeature, defaultValue float32)) *BloomFilterProviderInterface_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]interfaces.ModelFeature), args[2].(float32))
	})
	return _c
}

func (_c *BloomFilterProviderInterface_Provide_Call) Return(modelResult *interfaces.ModelResult, err error) *BloomFilterProviderInterface_Provide_Call {
	_c.Call.Return(modelResult, err)
	return _c
}

func (_c *BloomFilterProviderInterface_Provide_Call) RunAndReturn(run func(modelIdentifier string, features []interfaces.ModelFeature, defaultValue float32) (*interfaces.ModelResult, error)) *BloomFilterProviderInterface_Provide_Call {
	_c.Call.Return(run)
	return _c
}
